### PR TITLE
documentation for 'ApplicationName' property restored

### PR DESCRIPTION
**Pull request by The-Alchemist**
It looks like the documentation for the 'ApplicationName' property disappeared: between 9.1 and 9.2:
* Before: http://jdbc.postgresql.org/documentation/91/connect.html#connection-parameters, 
* After: http://jdbc.postgresql.org/documentation/92/connect.html#connection-parameters

From the docs, it looks like the property was absorbed into the 'jaasApplicationName'.

It looks like the code still uses both 'jaasApplicationName' and  'ApplicationName', though:

```
pgjdbc> grep -r ApplicationName .
./doc/pgjdbc.xml:       <term><varname>jaasApplicationName</varname> = <type>String</type></term>
./doc/pgjdbc.xml:       <term><varname>ApplicationName</varname> = <type>String</type></term>
./org/postgresql/core/v2/ConnectionFactoryImpl.java:        String appName = info.getProperty("ApplicationName");
./org/postgresql/core/v3/ConnectionFactoryImpl.java:                String appName = info.getProperty("ApplicationName");
./org/postgresql/core/v3/ConnectionFactoryImpl.java:                                    info.getProperty("jaasApplicationName"),
./org/postgresql/core/v3/ConnectionFactoryImpl.java:        String appName = info.getProperty("ApplicationName");
./org/postgresql/Driver.java.in:                { "jaasApplicationName", Boolean.FALSE,
./org/postgresql/ds/common/BaseDataSource.java:    public void setApplicationName(String applicationName)
./org/postgresql/ds/common/BaseDataSource.java:    public String getApplicationName()
./org/postgresql/ds/common/BaseDataSource.java:            sb.append("&ApplicationName=");
./org/postgresql/ds/common/BaseDataSource.java:     	applicationName = p.getProperty("ApplicationName");
./org/postgresql/ds/common/BaseDataSource.java:            ref.add(new StringRefAddr("ApplicationName", applicationName));
./org/postgresql/gss/MakeGSS.java:    public static void authenticate(PGStream pgStream, String host, String user, String password, String jaasApplicationName, String kerberosServerName, Logger logger, boolean useSpnego) throws IOException, SQLException
./org/postgresql/gss/MakeGSS.java:        if (jaasApplicationName == null)
./org/postgresql/gss/MakeGSS.java:            jaasApplicationName = "pgjdbc";
./org/postgresql/gss/MakeGSS.java:                LoginContext lc = new LoginContext(jaasApplicationName, new GSSCallbackHandler(user, password));
./org/postgresql/jdbc4/AbstractJdbc4Connection.java:            String appName = info.getProperty("ApplicationName");
./org/postgresql/jdbc4/AbstractJdbc4Connection.java:            _clientInfo.put("ApplicationName", appName);
./org/postgresql/jdbc4/AbstractJdbc4Connection.java:        if (haveMinimumServerVersion("9.0") && "ApplicationName".equals(name)) {
./org/postgresql/jdbc4/AbstractJdbc4Connection.java:                throw new SQLClientInfoException(GT.tr("Failed to set ClientInfo property: {0}", "ApplicationName"), sqle.getSQLState(), failures, sqle);
./org/postgresql/jdbc4/AbstractJdbc4Connection.java:        for (String name : new String[] { "ApplicationName" })
./org/postgresql/jdbc4/AbstractJdbc4DatabaseMetaData.java:            tuple[0] = connection.encodeString("ApplicationName");
./org/postgresql/test/jdbc4/ClientInfoTest.java:        _conn.setClientInfo("ApplicationName", "my app");
./org/postgresql/test/jdbc4/ClientInfoTest.java:        assertEquals("my app", _conn.getClientInfo("ApplicationName"));
./org/postgresql/test/jdbc4/ClientInfoTest.java:        assertEquals("my app", _conn.getClientInfo().getProperty("ApplicationName"));
./org/postgresql/test/jdbc4/ClientInfoTest.java:        props.put("ApplicationName", "my app");
./org/postgresql/test/jdbc4/ClientInfoTest.java:        assertEquals("my app", _conn.getClientInfo("ApplicationName"));
./org/postgresql/test/jdbc4/ClientInfoTest.java:        assertEquals("my app", _conn.getClientInfo().getProperty("ApplicationName"));
./org/postgresql/test/jdbc4/ClientInfoTest.java:        _conn.setClientInfo("ApplicationName", "my app");
./org/postgresql/test/jdbc4/ClientInfoTest.java:        String applicationName = _conn.getClientInfo("ApplicationName");
./org/postgresql/test/jdbc4/DatabaseMetaDataTest.java:        assertEquals("ApplicationName", rs.getString("NAME"));
>
```

### CODE REVIEW

**Comment by kjurka** [comment]
I've committed a change to put this back in the right place.  Thanks.

**Comment by The-Alchemist** [comment]
Looks like it's the ApplicationName property is gone from the 9.3 version of the docs too: http://jdbc.postgresql.org/documentation/93/connect.html#connection-parameters

**Comment by kjurka** [comment]
Yes, my commit got that place as well.  I'm not sure how/when the website gets updated, so it hasn't appeared yet, but at least the source is right now.

**Comment by davecramer** [comment]
The site needs to be manually updated. The machine that it lives on does
not have the capability of automatically updating itself

Dave Cramer

**Comment by The-Alchemist** [comment]
May I offer a suggestion of using the GitHub Pages (https://pages.github.com/) for documentation?  e.g., http://jmockit.github.io/tutorial.html

**Comment by davecramer** [comment]
While attractive, that is not an option. Thanks though

Dave Cramer

**Pull request closed without merging**
