### PR TITLE
docs: parameter "database" is optional

### LINKED ISSUE #9: README.md misses the fact that "database" parameter is optional
Acutally it is possible to connect without providing "database" parameter in the URL. PostgreSQL server will then try to connect to a database named like the "username" attempting the connect.

Will provide PR in few minutes.

### PR DESCRIPTION
**Pull request by mkarg**
PostgreSQL server accepts empty "database" parameter and
will default it to "username".

Closes #9

### CODE REVIEW

**Comment by quipsy-karg** [comment]
@davecramer What do I have to do to make this merged contribution actually appear live at https://jdbc.postgresql.org/documentation/head/connect.html?

**Comment by davecramer** [comment]
Well it's more what I have to do ... Because we are using the pg
infrastructure and they aren't particularly embracing github it's pretty
much a manual process.

Which means I have to find the time to do it. I will get around to it, but
during the week (when I'm not at pgcon) time is more precious .

Thanks, I will do it

Dave

Dave Cramer

**Comment by mkarg** [comment]
@davecramer Great, thanks! And have fun at pgcon! Maybe we should think about a way to automate the process?

**Comment by davecramer** [comment]
pgcon was last week.

Dave Cramer

**Comment by mkarg** [comment]
@davecramer Oops. ;-)

**Pull request merged**
